### ISSUE TITLE
In a SPA how to reset the query when there is a change of routes?

### ISSUE THREAD

**Issue by mynomoto** [district0x/district-ui-graphql#1]
I think that stop/restart should work, is that the way to do it?

**Comment by madvas** [comment]
Can you explain what you mean by resetting the query? Cancelling ongoing request to the server?

**Comment by mynomoto** [comment]
When I do a subscribe the query is cached on the dataloader right? If I load another view and do another query, I'm not interested in the previous one but will the dataloader fetch the previous query again?

**Comment by madvas** [comment]
Dataloader operates on single render of page. It will never have queries in queue from 2 different pages, because 2 different pages are 2 subsequent renders with little delay in-between.

**Comment by mynomoto** [comment]
Ok, thanks!
