### ISSUE TITLE
Dependency on print-foo-cljs

### ISSUE THREAD

**Issue by cnirrad** [district0x/district-ui-graphql#4]
I've tried to add this to my clojurescript project and I'm getting compilation errors because print/foo is missing. It is declared as a dev dependency, but this should be moved to a regular dependency.

Failed to compile "target/cljsbuild/public/js/app.js" in 4.566 seconds.
----  Could not Analyze  target/cljsbuild/public/js/out/district/ui/graphql/utils.cljs  ----

  Could not locate print/foo__init.class or print/foo.clj on classpath.

----  Analysis Error : Please see target/cljsbuild/public/js/out/district/ui/graphql/utils.cljs  ----

**Comment by madvas** [comment]
whoops, fixed in 1.0.2
